package com.bajinho.continuebeans.ai;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class NetBeansFunctionExecutorTest {
 @TempDir Path tempDir;
 private final NetBeansFunctionExecutor executor=new NetBeansFunctionExecutor();
 @Test void unknownFunctionReturnsError(){var r=execute("does_not_exist",Map.of());assertFalse(r.isSuccess());assertEquals("Unknown function: does_not_exist",r.getMessage());assertTrue(r.getData().isEmpty());}
 @Test void createFileCreatesParentDirectoriesAndContent() throws Exception {Path f=tempDir.resolve("nested/project/example.txt");var r=execute("create_file",Map.of("filePath",f.toString(),"content","hello"));assertTrue(r.isSuccess());assertTrue(Files.exists(f));assertEquals("hello",Files.readString(f));assertEquals(f.toString(),r.getData().get("filePath"));assertEquals(true,r.getData().get("created"));assertEquals(5,r.getData().get("size"));}
 @Test void createFileRefusesExistingFileWithoutOverwrite() throws Exception {Path f=tempDir.resolve("existing.txt");Files.writeString(f,"original");var r=execute("create_file",Map.of("filePath",f.toString(),"content","replacement"));assertFalse(r.isSuccess());assertTrue(r.getMessage().contains("File already exists"));assertEquals("original",Files.readString(f));}
 @Test void createFileOverwritesWhenRequested() throws Exception {Path f=tempDir.resolve("existing.txt");Files.writeString(f,"original");var r=execute("create_file",Map.of("filePath",f.toString(),"content","replacement","overwrite",true));assertTrue(r.isSuccess());assertEquals("replacement",Files.readString(f));}
 @Test void readFileReturnsContentAndMetadata() throws Exception {Path f=tempDir.resolve("read.txt");Files.writeString(f,"Olá NetBeans",StandardCharsets.UTF_8);var r=execute("read_file",Map.of("filePath",f.toString()));assertTrue(r.isSuccess());assertEquals("Olá NetBeans",r.getData().get("content"));assertEquals("UTF-8",r.getData().get("encoding"));assertEquals("success",r.getData().get("status"));}
 @Test void readMissingFileReturnsError(){var r=execute("read_file",Map.of("filePath",tempDir.resolve("missing.txt").toString()));assertFalse(r.isSuccess());assertTrue(r.getMessage().startsWith("File not found:"));}
 @Test void updateFileReplacesContentByDefault() throws Exception {Path f=tempDir.resolve("update.txt");Files.writeString(f,"before");var r=execute("update_file",Map.of("filePath",f.toString(),"content","after"));assertTrue(r.isSuccess());assertEquals("after",Files.readString(f));assertEquals(false,r.getData().get("append"));}
 @Test void updateFileCanAppend() throws Exception {Path f=tempDir.resolve("append.txt");Files.writeString(f,"before");var r=execute("update_file",Map.of("filePath",f.toString(),"content","-after","append",true));assertTrue(r.isSuccess());assertEquals("before-after",Files.readString(f));assertEquals(true,r.getData().get("append"));}
 @Test void updateMissingFileReturnsError(){var r=execute("update_file",Map.of("filePath",tempDir.resolve("missing.txt").toString(),"content","x"));assertFalse(r.isSuccess());assertTrue(r.getMessage().startsWith("File not found:"));}
 @Test void deleteRequiresExplicitConfirmation() throws Exception {Path f=tempDir.resolve("delete.txt");Files.writeString(f,"delete me");var r=execute("delete_file",Map.of("filePath",f.toString()));assertFalse(r.isSuccess());assertTrue(r.getMessage().contains("Confirmation required"));assertTrue(Files.exists(f));}
 @Test void deleteFileRemovesConfirmedFile() throws Exception {Path f=tempDir.resolve("delete.txt");Files.writeString(f,"delete me");var r=execute("delete_file",Map.of("filePath",f.toString(),"confirm",true));assertTrue(r.isSuccess());assertFalse(Files.exists(f));}
 @Test void deleteMissingFileReturnsError(){var r=execute("delete_file",Map.of("filePath",tempDir.resolve("missing.txt").toString(),"confirm",true));assertFalse(r.isSuccess());assertTrue(r.getMessage().startsWith("File not found:"));}
 @Test void listDirectorySupportsRecursiveTraversal() throws Exception {Path nested=Files.createDirectories(tempDir.resolve("nested"));Files.writeString(tempDir.resolve("root.txt"),"root");Files.writeString(nested.resolve("child.txt"),"child");var r=execute("list_directory",Map.of("directoryPath",tempDir.toString(),"recursive",true));assertTrue(r.isSuccess());assertEquals(true,r.getData().get("recursive"));assertEquals(2,r.getData().get("count"));}
 @Test void listDirectoryRejectsMissingDirectory(){var r=execute("list_directory",Map.of("directoryPath",tempDir.resolve("missing").toString()));assertFalse(r.isSuccess());assertTrue(r.getMessage().startsWith("Directory not found:"));}
 @Test void projectOperationsRejectMissingDirectories(){String p=tempDir.resolve("missing-project").toString();assertFalse(execute("get_project_info",Map.of("projectPath",p)).isSuccess());assertFalse(execute("build_project",Map.of("projectPath",p)).isSuccess());}
 @Test void buildRejectsDirectoryWithoutPom() throws Exception {Path p=Files.createDirectory(tempDir.resolve("project"));var r=execute("build_project",Map.of("projectPath",p.toString()));assertFalse(r.isSuccess());assertEquals("Not a Maven project: pom.xml not found",r.getMessage());}
 @Test void createProjectBuildsExpectedMavenLayout() throws Exception {var r=execute("create_project",Map.of("projectName","demo","projectType","maven","packageName","com.example.demo","location",tempDir.toString()));assertTrue(r.isSuccess());Path p=tempDir.resolve("demo");assertTrue(Files.exists(p.resolve("pom.xml")));assertTrue(Files.isDirectory(p.resolve("src/main/java/com/example/demo")));assertTrue(Files.isDirectory(p.resolve("src/test/java/com/example/demo")));}
 @Test void createProjectRejectsExistingDirectory() throws Exception {Path p=Files.createDirectory(tempDir.resolve("demo"));var r=execute("create_project",Map.of("projectName",p.getFileName().toString(),"packageName","com.example","location",tempDir.toString()));assertFalse(r.isSuccess());assertTrue(r.getMessage().contains("Project directory already exists"));}
 @Test void codeGenerationProducesObservableJavaSource(){var c=execute("generate_class",Map.of("className","Customer","packageName","com.example"));var i=execute("generate_interface",Map.of("interfaceName","CustomerRepository","packageName","com.example"));var t=execute("generate_test_method",Map.of("className","Customer"));assertTrue(c.isSuccess());assertTrue(((String)c.getData().get("content")).contains("public class Customer"));assertTrue(i.isSuccess());assertTrue(((String)i.getData().get("content")).contains("public interface CustomerRepository"));assertTrue(t.isSuccess());}
 @Test void analyzeCodeReturnsBasicMetrics() throws Exception {Path f=tempDir.resolve("Sample.java");Files.writeString(f,"class Sample {\n public void run() {}\n}\n");var r=execute("analyze_code",Map.of("filePath",f.toString()));assertTrue(r.isSuccess());assertEquals(3,r.getData().get("linesOfCode"));assertEquals(1,r.getData().get("classes"));assertEquals("completed",r.getData().get("status"));}
 @Test void analyzeAndRefactorRejectMissingFile(){String f=tempDir.resolve("missing.java").toString();assertFalse(execute("analyze_code",Map.of("filePath",f)).isSuccess());assertFalse(execute("refactor_code",Map.of("filePath",f)).isSuccess());}
 @Test void refactorCodeAppliesImportOptimization() throws Exception {Path f=tempDir.resolve("Refactor.java");Files.writeString(f,"import java.util.List;\nclass Refactor {}\n");var r=execute("refactor_code",Map.of("filePath",f.toString()));assertTrue(r.isSuccess());assertTrue(Files.readString(f).contains("// Imports optimized"));assertEquals("optimize_imports",r.getData().get("refactoringType"));}
 @Test void addDependencyBuildsDependencyXml(){var r=execute("add_dependency",Map.of("groupId","org.example","artifactId","demo","version","1.2.3"));assertTrue(r.isSuccess());assertEquals("org.example",r.getData().get("groupId"));assertTrue(((String)r.getData().get("dependencyXml")).contains("<artifactId>demo</artifactId>"));}
 @Test void editorOperationsRejectMissingFiles(){String f=tempDir.resolve("missing.java").toString();assertFalse(execute("open_editor",Map.of("filePath",f)).isSuccess());assertFalse(execute("close_editor",Map.of("filePath",f)).isSuccess());assertFalse(execute("save_editor",Map.of("filePath",f)).isSuccess());}
 @Test void moduleLookupReportsUnknownModuleWithoutThrowing(){var r=execute("get_module_info",Map.of("moduleCodeName","com.example.missing.module"));assertFalse(r.isSuccess());assertTrue(r.getMessage().contains("Module not found"));}
 private NetBeansFunctionExecutor.FunctionResult execute(String fn,Map<String,Object> args){return executor.executeFunction(fn,args).join();}
}
